### ISSUE TITLE
Cannot import multiple files with with JSON reference

### ISSUE THREAD

**Issue by fenuks** [boschni/json-merger#19]
Hello,
I have two files:
```yml
# a.yml
paths:
  /a1:
    description: Taken from a.yml.
  /a2:
    description: Taken from a.yml.
```
and
```yml
# b.yml
paths:
  /b1:
    description: Taken from b.yml.
  /b2:
    description: Taken from b.yml.
```
I want to import their corresponding values form `path` key to final file, like so:
```yml
# c.yml
paths:
  $import: ['a.yml#/paths', 'b.yml#/paths']
```
```sh
$ json-merger c.yml --pretty
{
        "paths": {
                "/b1": {
                        "description": "Taken from b.yml."
                },
                "/b2": {
                        "description": "Taken from b.yml."
                }
        }
}
```
Importing files without JSON path works fine, except having additional unwanted `path` key (real file is more complicated, and has more than one key in it, I would like to merge multiple standalone OpenApi definitions into one, for convenience).
```yml
# d.yml
paths:
  $import: ['a.yml', 'b.yml']
```
```sh
$ json-merger d.yml --pretty
{
        "paths": {
                "paths": {
                        "/a1": {
                                "description": "Taken from a.yml."
                        },
                        "/a2": {
                                "description": "Taken from a.yml."
                        },
                        "/b1": {
                                "description": "Taken from b.yml."
                        },
                        "/b2": {
                                "description": "Taken from b.yml."
                        }
                }
        }
}
```
There is no example in docs of importing multiple files with JSON path specified, therefore I am not certain whether it is a bug, or intended behaviour, but I suppose it is the latter.
